# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0005_stripetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripetoken',
            name='stripeBillingAddressCity',
        ),
        migrations.RemoveField(
            model_name='stripetoken',
            name='stripeBillingAddressCountry',
        ),
        migrations.RemoveField(
            model_name='stripetoken',
            name='stripeBillingAddressLine1',
        ),
        migrations.RemoveField(
            model_name='stripetoken',
            name='stripeBillingAddressState',
        ),
        migrations.RemoveField(
            model_name='stripetoken',
            name='stripeBillingName',
        ),
    ]
