# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0006_auto_20160401_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripetoken',
            name='stripeBillingAddressZip',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
