# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0007_auto_20160401_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripetoken',
            name='stripeBillingAddressZip',
        ),
    ]
