# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0008_remove_stripetoken_stripebillingaddresszip'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulklookup',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulklookup',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulklookup',
            name='last_error',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulklookup',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripetoken',
            name='bulk_lookup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_token', to='mapit_bulk_processing.BulkLookup'),
        ),
    ]
