# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0009_auto_20160401_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeToken', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('bulk_lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_charge', to='mapit_bulk_processing.BulkLookup')),
            ],
        ),
        migrations.RemoveField(
            model_name='stripetoken',
            name='bulk_lookup',
        ),
        migrations.DeleteModel(
            name='StripeToken',
        ),
    ]
