# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0010_auto_20160401_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecharge',
            name='bulk_lookup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_charge', to='mapit_bulk_processing.BulkLookup'),
        ),
    ]
