# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_bulk_processing', '0011_auto_20160401_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulklookup',
            name='output_file',
            field=models.FileField(blank=True, upload_to=b'output_files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='outputoption',
            name='mapit_area_type',
            field=models.CharField(default='WMC', max_length=256),
            preserve_default=False,
        ),
    ]
